### ISSUE TITLE
Primer isue

### ISSUE THREAD

**Issue by DJoser** [DJoser/HolaGitHub#2]
hacer algo en especial

**Comment by rickichon** [comment]
algo

**Comment by DJoser** [comment]
@rickichon que es lo que estas buscando

**Comment by DJoser** [comment]
# Hola esta es una prueba de titulo
<img width="344" alt="captura" src="https://cloud.githubusercontent.com/assets/10660174/12534251/44e111e6-c215-11e5-9c18-6241f04a5453.PNG">

**Comment by rickichon** [comment]
Respuesta
![prueba](https://cloud.githubusercontent.com/assets/16848289/12534256/5f5f6f7c-c215-11e5-9368-28031243b716.png)

**Comment by DJoser** [comment]
#3 ese tema ya se soluciono en esta discucion

**Comment by rickichon** [comment]
#1
