### ISSUE TITLE
Cambiar imagen del robotcito

### ISSUE THREAD

**Issue by lomasiltre23** [DJoser/HolaGitHub#5]
![logo](https://cloud.githubusercontent.com/assets/10999588/12534983/483fddb4-c237-11e5-9932-95bb75879a0c.png)

Cambiar esa imagen por esta:
![horda](https://cloud.githubusercontent.com/assets/10999588/12534988/862e3ed6-c237-11e5-8111-7d96eede511f.png)

**Comment by DJoser** [comment]
esta bien culera

**Comment by lomasiltre23** [comment]
Se ve mas chida!

**Comment by lomasiltre23** [comment]
Para que combine con esta tarea #6
